// src/components/TimerComponent.tsx
import { useAppDispatch } from './Store/hooks'
import { updateActiveTaskSeconds } from './Store/slices/activeTasks'
import { FC, useRef, useEffect } from 'react';
import { getHMSStringFromSeconds } from './../lib/Utils';

interface BaseLayoutProps {
  task: DBTask | ActiveTask;
}

export const TimerComponent: FC<BaseLayoutProps> = ({ task }) => {
  const dispatch = useAppDispatch();
  const ref = useRef<HTMLDivElement>(null);
  let tick: NodeJS.Timeout | null = null;
  let s = task.seconds;

  useEffect(() => {
    if ('isActive' in task && task.isActive) {
      if (ref.current) {
        tick = setInterval(() => {
          s++;
          dispatch(
            updateActiveTaskSeconds({
              name: task.name,
              project_name: task.project_name,
              date: task.date,
              seconds: s,
            })
          );
          ref.current.innerHTML = getHMSStringFromSeconds(s);
        }, 1000);
      }
    }
    return () => {
      if (tick) clearInterval(tick);
    }
  }, [task])
  return (
    <div ref={ref}>{getHMSStringFromSeconds(task.seconds)}</div>
  )
}

// src/renderer/src/components/TimerComponent.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte'
  import { getHMSStringFromSeconds } from '../lib/utils'
  import { activeTasks } from '../stores'

  export let task: DBTask | ActiveTask

  let displayTime = getHMSStringFromSeconds(task.seconds)
  let intervalId: ReturnType<typeof setInterval> | null = null
  let localSeconds = task.seconds

  $: isActive = 'isActive' in task && task.isActive
  $: currentSeconds = task.seconds

  // Update local seconds when task seconds change (but not when active, to avoid resetting during count)
  $: if (!isActive && currentSeconds !== undefined) {
    localSeconds = currentSeconds
    displayTime = getHMSStringFromSeconds(localSeconds)
  }

  // Start/stop interval based on isActive
  $: {
    if (isActive) {
      // Start interval if not already running
      if (!intervalId) {
        localSeconds = currentSeconds
        intervalId = setInterval(() => {
          localSeconds++
          displayTime = getHMSStringFromSeconds(localSeconds)
          // Update the active task in store
          activeTasks.update(tasks =>
            tasks.map(t =>
              t.name === task.name &&
              t.project_name === task.project_name &&
              t.date === task.date
                ? { ...t, seconds: localSeconds }
                : t,
            ),
          )
        }, 1000)
      }
    } else {
      // Stop interval if running
      if (intervalId) {
        clearInterval(intervalId)
        intervalId = null
        displayTime = getHMSStringFromSeconds(localSeconds)
      }
    }
  }

  onDestroy(() => {
    if (intervalId) {
      clearInterval(intervalId)
    }
  })
</script>

<div>{displayTime}</div>
