// src/components/EditTaskModal.tsx
import React, { FC, useRef } from 'react';
import { connect } from 'react-redux';
import { RootState } from './Store';
import { TimeInputComponent } from './TimeInputComponent';
import { InfoboxComponent } from './InfoboxComponent';
import { useAppDispatch } from './Store/hooks';
import { replaceActiveTask } from './Store/slices/activeTasks';
import { replaceTask } from './Store/slices/tasks';

interface BaseLayoutProps {
  activeTasks: ActiveTask[];
  task: DBTask;
  callback?: (status: boolean, editedTaskData?: DBTask) => void;
}

const Component: FC<BaseLayoutProps> = ({ activeTasks, callback, task }) => {
  const ref = useRef<HTMLFormElement>(null)
  const dispatch = useAppDispatch();

  const onEditButtonClick = async (evt: React.MouseEvent) => {
    evt.preventDefault();
    const form = ref.current;
    const formData = new FormData(form);
    const description = formData.get("description") as string
    const seconds = formData.get("seconds") as string

    const rpcResult = await window.electron.editTask({
      name: task.name,
      description,
      project_name: task.project_name,
      seconds: parseInt(seconds, 10),
      date: task.date
    })

    if (rpcResult.success) {
      const activeTask = activeTasks.find((at) => at.name === task.name && at.project_name === task.project_name && at.date === task.date)
      if (activeTask) {
        dispatch(replaceActiveTask({
          name: rpcResult.name,
          oldname: rpcResult.name,
          project_name: rpcResult.project_name,
          description: rpcResult.description,
          date: rpcResult.date,
          seconds: rpcResult.seconds,
          isActive: activeTask.isActive
        }))
      }
      dispatch(replaceTask({
        name: rpcResult.name,
        oldname: rpcResult.name,
        seconds: rpcResult.seconds,
        project_name: rpcResult.project_name,
        date: rpcResult.date,
        description: rpcResult.description,
      }))
    }

    callback && callback(true, {
      name: task.name,
      project_name: task.project_name,
      description,
      seconds: parseInt(seconds),
      date: task.date
    })
  }

  const onCancelButtonClick = (evt: React.MouseEvent) => {
    evt.preventDefault();
    callback && callback(false)
  }

  const activeTask = activeTasks.find(t => t.name === task.name && t.date === task.date && t.project_name === task.project_name)

  return <>
    <div className="modal is-active">
      <div className="modal-background"></div>
      <div className="modal-card">
          <form ref={ref}>
            <header className="modal-card-head">
              <p className="modal-card-title">Edit Task</p>
            </header>
            <section className="modal-card-body">
              <div className="field">
                <label className="label">Task Description</label>
                <div className="control">
                  <textarea name="description" className="textarea" placeholder="Task Description" defaultValue={task.description}></textarea>
                </div>
              </div>
              <div className="field">
                <label className="label">Task Duration</label>
                <div className="control">
                  { (activeTask !== undefined) ?
                    <>
                      <InfoboxComponent title="Warning" type="warning" collapsed={true}>
                        Editing the <strong>duration</strong> of an <strong>active task</strong> is not allowed.
                        You can stop the task first, and then edit the duration.
                      </InfoboxComponent>
                      <TimeInputComponent task={activeTask} />
                    </>
                    : <TimeInputComponent task={task} addUpHours={true} />
                }
                </div>
              </div>
            </section>
            <footer className="modal-card-foot">
              <div data-buttons className="buttons">
                <button type="submit" className="button is-warning" onClick={onEditButtonClick}>Edit</button>
                <button className="button" onClick={onCancelButtonClick}>Cancel</button>
              </div>
            </footer>
          </form>
      </div>
    </div>
  </>;
};

const mapStateToProps = (state: RootState) => {
  return {
    activeTasks: state.activeTasks.value
  }
}
const connected = connect(mapStateToProps)(Component);
export const EditTaskModal = connected

// src/renderer/src/components/modals/EditTaskModal.svelte
<script lang="ts">
  import { activeTasks, tasks } from '../../stores'
  import InfoBox from '../InfoBox.svelte'

  export let task: DBTask
  export let onClose: (success: boolean, editedTask?: DBTask) => void

  let description = task.description
  let hours = Math.floor(task.seconds / 3600)
  let minutes = Math.floor((task.seconds % 3600) / 60)
  let seconds = task.seconds % 60
  let date = task.date
  let status = task.status || 'active'
  const oldDate = task.date

  $: activeTask = $activeTasks.find(
    at =>
      at.name === task.name &&
      at.project_name === task.project_name &&
      at.date === oldDate,
  )

  $: isActive = activeTask !== undefined && activeTask.isActive
  $: currentSeconds = hours * 3600 + minutes * 60 + seconds

  async function handleSubmit(e: Event) {
    e.preventDefault()
    if (window.electron) {
      const result = await window.electron.editTask({
        name: task.name,
        description,
        project_name: task.project_name,
        seconds: currentSeconds,
        date: date,
        old_date: oldDate,
        status,
      })

      if (result.success) {
        // Update active tasks if task is active
        if (activeTask) {
          await activeTasks.update(ats =>
            ats.map(at =>
              at.name === task.name &&
              at.project_name === task.project_name &&
              at.date === oldDate
                ? { ...at, description, seconds: currentSeconds, date: date }
                : at,
            ),
          )
        }

        // Pass edited task back to parent - parent will refresh from database
        onClose(true, {
          ...task,
          description,
          seconds: currentSeconds,
          date: date,
          status,
        })
      }
    }
  }

  function handleCancel() {
    onClose(false)
  }
</script>

<div class="modal modal-open">
  <div class="modal-box">
    <h3 class="font-bold text-lg">Edit Task</h3>
    <form on:submit={handleSubmit}>
      <div class="form-control mt-4">
        <label class="label">
          <span class="label-text">Task Description</span>
        </label>
        <textarea
          bind:value={description}
          class="textarea textarea-bordered"
          placeholder="Task Description"
        ></textarea>
      </div>
      <div class="form-control mt-4">
        <label class="label">
          <span class="label-text">Task Date</span>
        </label>
        {#if isActive}
          <InfoBox type="warning" title="Warning">
            Editing the <strong>date</strong> of an
            <strong>active task</strong> is not allowed. You can stop the task first,
            and then edit the date.
          </InfoBox>
        {/if}
        <input
          type="date"
          bind:value={date}
          class="input input-bordered"
          disabled={isActive}
          required
        />
      </div>
      <div class="form-control mt-4">
        <label class="label">
          <span class="label-text">Task Duration</span>
        </label>
        {#if isActive}
          <InfoBox type="warning" title="Warning">
            Editing the <strong>duration</strong> of an
            <strong>active task</strong> is not allowed. You can stop the task first,
            and then edit the duration.
          </InfoBox>
        {/if}
        <div class="grid grid-cols-3 gap-4">
          <div class="form-control">
            <label class="label">
              <span class="label-text">Hours</span>
            </label>
            <input
              type="number"
              bind:value={hours}
              min="0"
              class="input input-bordered"
              disabled={isActive}
            />
          </div>
          <div class="form-control">
            <label class="label">
              <span class="label-text">Minutes</span>
            </label>
            <input
              type="number"
              bind:value={minutes}
              min="0"
              max="59"
              class="input input-bordered"
              disabled={isActive}
            />
          </div>
          <div class="form-control">
            <label class="label">
              <span class="label-text">Seconds</span>
            </label>
            <input
              type="number"
              bind:value={seconds}
              min="0"
              max="59"
              class="input input-bordered"
              disabled={isActive}
            />
          </div>
        </div>
      </div>
      <div class="form-control mt-4">
        <label class="label">
          <span class="label-text">Status</span>
        </label>
        <select bind:value={status} class="select select-bordered" required>
          <option value="active">Active</option>
          <option value="inactive">Inactive</option>
        </select>
      </div>
      <div class="modal-action">
        <button type="submit" class="btn btn-warning" disabled={isActive}
          >Edit</button
        >
        <button type="button" class="btn" on:click={handleCancel}>Cancel</button
        >
      </div>
    </form>
  </div>
  <div class="modal-backdrop" on:click={handleCancel}></div>
</div>
