// src/renderer/src/components/ActiveTasks.svelte
<script lang="ts">
  import { onMount } from 'svelte'
  import { activeTasks, tasks as tasksStore, selectedProject } from '../stores'
  import TimerComponent from './TimerComponent.svelte'

  let tasks: ActiveTask[] = []

  onMount(async () => {
    await fetchActiveTasks()

    // Listen for visibility changes
    document.addEventListener('visibilitychange', () => {
      if (!document.hidden) {
        fetchActiveTasks()
      }
    })
  })

  activeTasks.subscribe(value => {
    tasks = value
  })

  async function fetchActiveTasks() {
    if (window.electron) {
      try {
        tasks = await window.electron.getActiveTasks()
        activeTasks.set(tasks)
      } catch (error) {
        console.error('Error loading active tasks:', error)
      }
    }
  }

  async function handleStartTask(task: ActiveTask) {
    if (window.electron) {
      const result = await window.electron.startActiveTask({
        name: task.name,
        project_name: task.project_name,
        description: task.description,
        date: task.date,
        seconds: task.seconds,
      })
      if (result.success) {
        await fetchActiveTasks()
      }
    }
  }

  async function handleStopTask(task: ActiveTask) {
    if (window.electron) {
      const result = await window.electron.stopActiveTask({
        name: task.name,
        project_name: task.project_name,
        date: task.date,
      })
      if (result.success) {
        await fetchActiveTasks()
        // Refresh tasks list to show updated time
        const selectedProj = $selectedProject
        if (selectedProj.name && selectedProj.name === task.project_name) {
          try {
            const updatedTasks = await window.electron.getTasksToday(
              selectedProj.name,
            )
            tasksStore.set(updatedTasks)
          } catch (error) {
            console.error('Error refreshing tasks after stop:', error)
          }
        }
      }
    }
  }

  async function handlePauseTask(task: ActiveTask) {
    if (window.electron) {
      const result = await window.electron.pauseActiveTask({
        name: task.name,
        project_name: task.project_name,
        description: task.description,
        date: task.date,
        seconds: task.seconds,
      })
      if (result.success) {
        await fetchActiveTasks()
      }
    }
  }
</script>

{#if tasks.length > 0}
  <section class="section">
    <div class="card bg-base-200 shadow-xl">
      <div class="card-body">
        <h2 class="card-title">Active Tasks</h2>
        <div class="overflow-x-auto">
          <table class="table">
            <thead>
              <tr>
                <th>Project</th>
                <th>Task Name</th>
                <th>Task Elapsed</th>
                <th>Task Date</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {#each tasks as task}
                <tr>
                  <td>{task.project_name}</td>
                  <td>{task.name}</td>
                  <td>
                    <TimerComponent {task} />
                  </td>
                  <td>{task.date}</td>
                  <td>
                    {#if task.isActive}
                      <button
                        class="btn btn-warning btn-sm mr-2"
                        on:click={() => handlePauseTask(task)}
                      >
                        Pause
                      </button>
                    {:else}
                      <button
                        class="btn btn-success btn-sm mr-2"
                        on:click={() => handleStartTask(task)}
                      >
                        Resume
                      </button>
                    {/if}
                    <button
                      class="btn btn-error btn-sm"
                      on:click={() => handleStopTask(task)}
                    >
                      Stop
                    </button>
                  </td>
                </tr>
              {/each}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </section>
{/if}

// src/components/ActiveTasks.tsx
import { FC, useEffect } from 'react';
import { connect } from 'react-redux';
import type { RootState } from './Store'
import { useAppDispatch } from './Store/hooks'
import { removeActiveTask, replaceActiveTasks, replaceActiveTask, pauseActiveTask } from './Store/slices/activeTasks'
import { replaceTask } from './Store/slices/tasks'
import { TimerComponent } from './TimerComponent';

interface BaseLayoutProps {
  activeTasks: ActiveTask[]
}

const Component: FC<BaseLayoutProps> = ({ activeTasks }) => {
  const dispatch = useAppDispatch();

  const fetchActiveTasks = async () => {
    const rpcResult = await window.electron.getActiveTasks();
    if (rpcResult && rpcResult.length) {
      dispatch(replaceActiveTasks(rpcResult));
    }
  }

  const onVisibilityChange = () => {
    document.addEventListener("visibilitychange", () => {
      if (!document.hidden) {
        // restoring from background
        // possible throttling of the UI might have happened
        // fetch active tasks again from backend
        fetchActiveTasks();
      }
    });
  }

  useEffect(() => {
    fetchActiveTasks();
    onVisibilityChange()
  }, []);

  const startTask = async (evt: React.MouseEvent) => {
    evt.preventDefault();
    const target = evt.target as HTMLButtonElement;
    const root = target.closest('tr');
    const rpcResult = await window.electron.startActiveTask({
      project_name: root.dataset.projectName,
      name: root.dataset.name,
      date: root.dataset.date,
      seconds: parseInt(root.dataset.seconds, 10),
      description: root.dataset.description,
    });
    if (rpcResult.success) {
      dispatch(replaceActiveTask({
        oldname: rpcResult.name,
        name: rpcResult.name,
        description: rpcResult.description,
        project_name: rpcResult.project_name,
        date: rpcResult.date,
        seconds: rpcResult.seconds,
        isActive: true,
      }));
    }
  }
  const stopTask = async (evt: React.MouseEvent) => {
    evt.preventDefault();
    const target = evt.target as HTMLButtonElement;
    const root = target.closest('tr');
    const rpcResult = await window.electron.stopActiveTask({
      project_name: root.dataset.projectName,
      name: root.dataset.name,
      date: root.dataset.date
    });
    if (rpcResult.success) {
      dispatch(removeActiveTask({
        name: rpcResult.name,
        project_name: rpcResult.project_name,
        date: rpcResult.date,
      }));
      dispatch(replaceTask({
        name: rpcResult.name,
        oldname: rpcResult.name,
        project_name: rpcResult.project_name,
        date: rpcResult.date,
        seconds: rpcResult.seconds,
        description: root.dataset.description,
      }));
    }
  }

  const pauseTask = async (evt: React.MouseEvent) => {
    evt.preventDefault();
    const target = evt.target as HTMLButtonElement;
    const root = target.closest('tr');
    const rpcResult = await window.electron.pauseActiveTask({
      project_name: root.dataset.projectName,
      name: root.dataset.name,
      description: root.dataset.description,
      date: root.dataset.date,
      seconds: parseInt(root.dataset.seconds, 10),
    });
    if (rpcResult.success) {
      dispatch(pauseActiveTask({
        name: root.dataset.name,
        project_name: root.dataset.projectName,
        date: root.dataset.date
      }));
    }
  }

  return <>
    { activeTasks.length ?
      <section className="section">
        <nav className="panel">
          <p className="panel-heading">Active Tasks</p>
          <div className="panel-block">
            <table className="table is-fullwidth">
              <thead>
                <tr>
                  <th>Project</th>
                  <th>Task Name</th>
                  <th>Task Elapsed</th>
                  <th>Task Date</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                {activeTasks.map((task, idx: number) => {
                  return <tr key={idx}
                    data-project-name={task.project_name}
                    data-name={task.name}
                    data-description={task.description}
                    data-seconds={task.seconds}
                    data-active={task.isActive}
                    data-date={task.date}
                  >
                    <td>{task.project_name}</td>
                    <td>{task.name}</td>
                    <td>
                      <TimerComponent task={task} />
                    </td>
                    <td>{task.date}</td>
                    <td>
                      { task.isActive ?
                        <button className="button is-warning is-small m-1" onClick={pauseTask}>Pause</button>
                        : <button className="button is-success is-small m-1" onClick={startTask}>Resume</button>
                      }
                      <button className="button is-danger is-small m-1" onClick={stopTask}>Stop</button>
                    </td>
                  </tr>
                })}
              </tbody>
            </table>
          </div>
        </nav>
      </section>
      : null }
  </>;
};

const mapStateToProps = (state: RootState) => {
  return { activeTasks: state.activeTasks.value }
}
const connected = connect(mapStateToProps)(Component);
export const ActiveTasks = connected
