// src/renderer/src/components/modals/EditProjectModal.svelte
<script lang="ts">
  import { projects, companies } from '../../stores'

  export let project: DBProject
  export let onClose: (success: boolean, editedProject?: DBProject) => void

  let projectName = project.name
  let companyName = project.company_name
  let status = project.status || 'active'

  async function handleSubmit(e: Event) {
    e.preventDefault()
    if (window.electron) {
      const result = await window.electron.editProject({
        oldname: project.name,
        name: projectName,
        company_name: companyName,
        status,
      })
      if (result.success) {
        await projects.update(ps =>
          ps.map(p =>
            p.name === project.name
              ? { name: projectName, company_name: companyName, status }
              : p,
          ),
        )
        onClose(true, { name: projectName, company_name: companyName, status })
      }
    }
  }

  function handleCancel() {
    onClose(false)
  }
</script>

<div class="modal modal-open">
  <div class="modal-box">
    <h3 class="font-bold text-lg">Edit Project</h3>
    <form on:submit={handleSubmit}>
      <div class="form-control mt-4">
        <label class="label">
          <span class="label-text">Project Name</span>
        </label>
        <input
          type="text"
          bind:value={projectName}
          class="input input-bordered"
          required
        />
      </div>
      <div class="form-control mt-4">
        <label class="label">
          <span class="label-text">Company</span>
        </label>
        <select
          bind:value={companyName}
          class="select select-bordered"
          required
        >
          {#each $companies as company}
            <option value={company.name}>{company.name}</option>
          {/each}
        </select>
      </div>
      <div class="form-control mt-4">
        <label class="label">
          <span class="label-text">Status</span>
        </label>
        <select bind:value={status} class="select select-bordered" required>
          <option value="active">Active</option>
          <option value="inactive">Inactive</option>
        </select>
      </div>
      <div class="modal-action">
        <button type="submit" class="btn btn-warning">Edit</button>
        <button type="button" class="btn" on:click={handleCancel}>Cancel</button
        >
      </div>
    </form>
  </div>
  <div class="modal-backdrop" on:click={handleCancel}></div>
</div>

// src/components/EditProjectModal.tsx
import React, { FC, ReactNode, useRef } from 'react';
import { replaceProject } from './Store/slices/projects'
import { useAppDispatch } from './Store/hooks'

interface BaseLayoutProps {
  children?: ReactNode;
  project: DBProject;
  callback?: (status: boolean, project?: DBProject) => void;
}

export const EditProjectModal: FC<BaseLayoutProps> = ({ callback, project }) => {
  const ref = useRef<HTMLFormElement>(null);
  const dispatch = useAppDispatch();

  const onEditButtonClick = async (evt: React.MouseEvent) => {
    evt.preventDefault();
    const form = ref.current as HTMLFormElement;
    const formData = new FormData(form);
    const oldname = formData.get("oldname") as string
    const name = formData.get("name") as string
    const rpcResult = await window.electron.editProject({ oldname, name })
    if (rpcResult.success) {
      dispatch(replaceProject({ name, oldname }));
    }
    callback && callback(true, { name });
  }

  const onCancelButtonClick = (evt: React.MouseEvent) => {
    evt.preventDefault();
    callback && callback(false);
  }

  return <>
    <div className="modal is-active">
      <div className="modal-background"></div>
      <div className="modal-card">
        <form ref={ref}>
          <header className="modal-card-head">
            <p className="modal-card-title">Edit Project</p>
          </header>
          <section className="modal-card-body">
            <div className="field">
              <label className="label">Project Name</label>
              <div className="control">
                <input type="hidden" name="oldname" defaultValue={project.name} />
                <input className="input" name="name" required defaultValue={project.name} type="text" placeholder="Project Name" />
              </div>
            </div>
          </section>
          <footer className="modal-card-foot">
            <div data-buttons className="buttons">
              <button className="button is-warning" onClick={onEditButtonClick}>Edit</button>
              <button className="button" onClick={onCancelButtonClick}>Cancel</button>
            </div>
          </footer>
        </form>
      </div>
    </div>
  </>;
};
