// src/renderer/src/components/Projects.svelte
<script lang="ts">
  import { onMount } from 'svelte'
  import {
    projects,
    selectedProject,
    selectedCompany,
    activeTasks,
    selectedTask,
    selectedTaskDefinition,
    projectsForSelectedCompany,
  } from '../stores'
  import EditProjectModal from './modals/EditProjectModal.svelte'
  import DeleteProjectModal from './modals/DeleteProjectModal.svelte'
  import InfoBox from './InfoBox.svelte'

  let projectsList: DBProject[] = []
  let showEditModal = false
  let showDeleteModal = false
  let projectToEdit: DBProject | null = null
  let projectToDelete: DBProject | null = null

  $: activeTasksList = $activeTasks
  $: selectedProj = $selectedProject
  $: selectedComp = $selectedCompany
  $: companyProjects = $projectsForSelectedCompany

  onMount(async () => {
    await fetchProjects()
  })

  projects.subscribe(value => {
    projectsList = value
  })

  selectedCompany.subscribe(async () => {
    if ($selectedCompany.name) {
      await fetchProjects($selectedCompany.name)
    } else {
      projects.set([])
    }
  })

  async function fetchProjects(companyName?: string) {
    if (window.electron) {
      try {
        const data = await window.electron.getProjects(companyName)
        projects.set(data)
      } catch (error) {
        console.error('Error loading projects:', error)
      }
    }
  }

  async function handleAddProject(e: Event) {
    e.preventDefault()
    const form = e.target as HTMLFormElement
    const formData = new FormData(form)
    const name = formData.get('name') as string

    if (name && $selectedCompany.name && window.electron) {
      const result = await window.electron.addProject(
        name,
        $selectedCompany.name,
      )
      if (result.success) {
        await fetchProjects($selectedCompany.name)
        form.reset()
      }
    }
  }

  function handleProjectSelect(project: DBProject) {
    selectedTask.set(null)
    selectedTaskDefinition.set(null)
    selectedProject.set({
      name: project.name,
      company_name: project.company_name,
    })
  }

  function handleEditClick(project: DBProject) {
    projectToEdit = project
    showEditModal = true
  }

  function handleDeleteClick(project: DBProject) {
    projectToDelete = project
    showDeleteModal = true
  }

  function handleEditModalClose(success: boolean, editedProject?: DBProject) {
    showEditModal = false
    if (success && editedProject) {
      selectedProject.set({
        name: editedProject.name,
        company_name: editedProject.company_name,
      })
      fetchProjects($selectedCompany.name)
    }
    projectToEdit = null
  }

  function handleDeleteModalClose(success: boolean) {
    showDeleteModal = false
    if (success) {
      selectedProject.set({ name: null, company_name: null })
      fetchProjects($selectedCompany.name)
    }
    projectToDelete = null
  }

  function hasActiveTask(projectName: string): boolean {
    return activeTasksList.some(at => at.project_name === projectName)
  }
</script>

{#if showEditModal && projectToEdit}
  <EditProjectModal project={projectToEdit} onClose={handleEditModalClose} />
{/if}

{#if showDeleteModal && projectToDelete}
  <DeleteProjectModal
    project={projectToDelete}
    onClose={handleDeleteModalClose}
  />
{/if}

<section class="section">
  <h1 class="text-2xl font-bold">Projects</h1>
  <h2 class="text-lg text-base-content/70">
    Manage your projects for {selectedComp.name || 'the selected company'}.
    Select a project to view its tasks.
  </h2>

  {#if !selectedComp.name}
    <InfoBox type="info" title="Select a Company">
      Please select a company first to view and manage its projects.
    </InfoBox>
  {:else}
    <div class="grid grid-cols-3 gap-4 mt-4">
      <!-- New Project -->
      <div class="card bg-base-200 shadow-xl">
        <div class="card-body">
          <h2 class="card-title">New</h2>
          <form on:submit={handleAddProject}>
            <div class="form-control">
              <label class="label">
                <span class="label-text">Project Name</span>
              </label>
              <input
                type="text"
                name="name"
                placeholder="Project Name"
                class="input input-bordered"
                required
              />
            </div>
            <div class="form-control mt-4">
              <button type="submit" class="btn btn-primary">Add Project</button>
            </div>
          </form>
        </div>
      </div>

      <!-- Available Projects -->
      <div class="card bg-base-200 shadow-xl">
        <div class="card-body">
          <h2 class="card-title">Available</h2>
          <div class="space-y-2">
            {#each companyProjects as project}
              <div
                class="p-3 rounded cursor-pointer transition-colors"
                class:bg-primary={selectedProj.name === project.name}
                class:text-primary-content={selectedProj.name === project.name}
                on:click={() => handleProjectSelect(project)}
              >
                <p class="font-semibold">{project.name}</p>
              </div>
            {/each}
          </div>
        </div>
      </div>

      <!-- Actions -->
      {#if selectedProj.name}
        <div class="card bg-base-200 shadow-xl">
          <div class="card-body">
            <h2 class="card-title">Actions</h2>
            {#if hasActiveTask(selectedProj.name)}
              <InfoBox type="warning" title="Warning">
                A task belonging to this project is currently active, you need
                to stop it to perform any action.
              </InfoBox>
            {:else}
              <div class="flex gap-2">
                <button
                  class="btn btn-warning"
                  on:click={() =>
                    handleEditClick({
                      name: selectedProj.name!,
                      company_name: selectedProj.company_name!,
                    })}
                >
                  Edit
                </button>
                <button
                  class="btn btn-error"
                  on:click={() =>
                    handleDeleteClick({
                      name: selectedProj.name!,
                      company_name: selectedProj.company_name!,
                    })}
                >
                  Delete
                </button>
              </div>
            {/if}
          </div>
        </div>
      {/if}
    </div>
  {/if}
</section>

// src/components/Projects.tsx
import { FC, useEffect, useState } from 'react';
import { useAppDispatch, useAppSelector } from './Store/hooks'
import { replaceProjects, appendProject } from './Store/slices/projects'
import { setSelectedProject, removeSelectedProject } from './Store/slices/selectedProject'
import { removeSelectedTaskDefinition } from './Store/slices/selectedTaskDefinition'
import { removeSelectedTask } from './Store/slices/selectedTask'
import { Datafetcher } from './../lib/Datafetcher';
import { DeleteProjectModal } from './DeleteProjectModal';
import { EditProjectModal } from './EditProjectModal';
import { InfoboxComponent } from './InfoboxComponent';
import clsx from 'clsx';
import { RootState } from './Store';
import { connect } from 'react-redux';

type Props = {
  activeTasks: ActiveTask[],
}


export const Component: FC<Props> = ({ activeTasks }) => {
  const dispatch = useAppDispatch();
  const projects = useAppSelector((state) => state.projects.value)
  const selectedProject = useAppSelector((state) => state.selectedProject.value)
  const [useModal, setModal] = useState<React.ReactNode>(null)

  const onFormSubmit = async (evt: React.FormEvent) => {
    evt.preventDefault();
    const form = evt.target as HTMLFormElement;
    const formData = new FormData(form);
    const name = formData.get("name") as string
    const rpcResult = await window.electron.addProject(name)
    if (rpcResult.success) {
      dispatch(appendProject({ name }));
    }
  }

  const onProjectSelect = async (evt: React.MouseEvent) => {
    const target = evt.target as HTMLDivElement
    const root = target.closest('[data-name]') as HTMLDivElement
    const name = root.dataset.name as string
    dispatch(removeSelectedTask())
    dispatch(removeSelectedTaskDefinition())
    dispatch(setSelectedProject({ name: name }))
  }

  const onConfirmCallback = async (status: boolean) => {
    if (status) {
      const project = projects.find((p) => p.name === selectedProject.name)
      if (project) {
        dispatch(removeSelectedProject());
      }
    }
    setModal(null)
  }

  const onDeleteButtonClick = async (evt: React.MouseEvent) => {
    evt.preventDefault();
    setModal(<DeleteProjectModal project={selectedProject} callback={onConfirmCallback} />)
  }

  const onEditProjectCallback = async (status: boolean, editedProjectData: DBProject) => {
    if (status) {
      dispatch(setSelectedProject({ name: editedProjectData.name }));
    }
    setModal(null)
  }

  const onEditButtonClick = async (evt: React.MouseEvent<HTMLButtonElement>) => {
    evt.preventDefault();
    // TODO - fix this - this is a problem when there is an associated task or task definition
    // active and we edit the project name ... we need to update the selected project name
    // in the redux store, but we also need to update the active tasks in the backend ...
    const data = JSON.parse(evt.currentTarget.dataset.data as string) as DBProject
    setModal(<EditProjectModal  project={data} callback={(status, data) => onEditProjectCallback(status, data)} />)
  }

  const fetchProjects = async () => {
    const ps = await Datafetcher.getProjects();
    dispatch(replaceProjects(ps))
  }

  const ButtonWrapperComponent: FC = () => {
    const activeTask = activeTasks.find((at) => at.project_name === selectedProject.name)
    if (activeTask) {
      return <>
        <InfoboxComponent title="Warning" type="warning">
          A task belonging to this project is currently active,
          you need to stop it to perform any action.
        </InfoboxComponent>
      </>
    } else {
      return <>
        <button className="button is-warning m-1" data-data={JSON.stringify(selectedProject)} onClick={onEditButtonClick}>Edit</button>
        <button className="button is-danger m-1" data-data={JSON.stringify(selectedProject)} onClick={onDeleteButtonClick}>Delete</button>
      </>
    }
  }


  useEffect(() => {
    fetchProjects();
  }, [])

  return <>
    {useModal}
    <section className="section">
      <h1 className="title">Projects</h1>
      <h2 className="subtitle">All available projects</h2>
      <div className="fixed-grid has-3-cols">
        <div className="grid">
          <div className="cell">
            <nav className="panel">
              <p className="panel-heading">New</p>
              <form className="p-4" onSubmit={onFormSubmit}>
                <div className="field">
                  <label className="label">Project Name</label>
                  <div className="control">
                    <input name="name" className="input" type="text" placeholder="Project Name" />
                  </div>
                </div>
                <div className="field">
                  <div className="control">
                    <button className="button is-primary" type="submit">Add Project</button>
                  </div>
                </div>
              </form>
            </nav>
          </div>
          <div className="cell">
            <nav className="panel">
              <p className="panel-heading">Available</p>
              <div>
                {projects.map((project, idx: number) => (
                  <div key={idx} className={clsx('panel-block', (project.name === selectedProject.name ? 'is-active' : null))} data-idx={idx} data-name={project.name} onClick={onProjectSelect}>
                    <p data-project-item-header className="bd-notification is-info">{project.name}</p>
                  </div>
                ))}
              </div>
            </nav>
          </div>
          {selectedProject.name !== null ?
          <div data-project-actions-container className="cell">
            <nav className="panel">
              <p className="panel-heading">Actions</p>
              <form data-buttons className="p-4">
                <div className="field">
                  <div className="control">
                    <ButtonWrapperComponent />
                  </div>
                </div>
              </form>
            </nav>
          </div>
        : null }
        </div>
      </div>
    </section>
  </>;
};

const mapStateToProps = (state: RootState) => {
  return {
    activeTasks: state.activeTasks.value,
  }
}

const connected = connect(mapStateToProps)(Component);
export const Projects = connected
