// src/renderer/src/components/Search.svelte
<script lang="ts">
  import moment from 'moment'
  import { activeTasks, searchResults } from '../stores'
  import EditCompanyModal from './modals/EditCompanyModal.svelte'
  import DeleteCompanyModal from './modals/DeleteCompanyModal.svelte'
  import EditProjectModal from './modals/EditProjectModal.svelte'
  import DeleteProjectModal from './modals/DeleteProjectModal.svelte'
  import EditTaskModal from './modals/EditTaskModal.svelte'
  import DeleteTaskModal from './modals/DeleteTaskModal.svelte'
  import EditTaskDefinitionModal from './modals/EditTaskDefinitionModal.svelte'
  import DeleteTaskDefinitionModal from './modals/DeleteTaskDefinitionModal.svelte'
  import InfoBox from './InfoBox.svelte'
  import { getHMSStringFromSeconds } from '../lib/utils'

  let searchResult: SearchQueryResult | null = $state(null)
  let loading = $state(false)
  let showEditCompanyModal = $state(false)
  let showDeleteCompanyModal = $state(false)
  let showEditProjectModal = $state(false)
  let showDeleteProjectModal = $state(false)
  let showEditTaskModal = $state(false)
  let showDeleteTaskModal = $state(false)
  let showEditTaskDefModal = $state(false)
  let showDeleteTaskDefModal = $state(false)

  let companyToEdit: DBCompany | null = $state(null)
  let companyToDelete: DBCompany | null = $state(null)
  let projectToEdit: DBProject | null = $state(null)
  let projectToDelete: DBProject | null = $state(null)
  let taskToEdit: DBTask | null = $state(null)
  let taskToDelete: DBTask | null = $state(null)
  let taskDefToEdit: DBTaskDefinition | null = $state(null)
  let taskDefToDelete: DBTaskDefinition | null = $state(null)

  // Form values
  let searchIn: string[] = $state([])
  let fromDate = $state(moment().format('YYYY-MM-DD'))
  let toDate = $state(moment().format('YYYY-MM-DD'))
  let activeState = $state('all')
  let companyName = $state('*')
  let projectName = $state('*')
  let taskName = $state('*')
  let taskDescription = $state('*')
  let taskDefinitionName = $state('*')

  let activeTasksList = $state($activeTasks)
  let formValid = $derived(false)

  $effect(() => {
    formValid =
      searchIn.length > 0 &&
      !!fromDate &&
      !!toDate &&
      !!activeState &&
      !!companyName &&
      !!projectName &&
      !!taskName &&
      !!taskDescription &&
      !!taskDefinitionName
  })

  async function handleSearch(e: Event) {
    e.preventDefault()
    if (!formValid) return

    loading = true
    searchResult = null

    try {
      const query: SearchQuery = {
        search_in: searchIn,
        from_date: fromDate,
        to_date: toDate,
        active_state: activeState,
        task: {
          company_name: companyName,
          project_name: projectName,
          task_name: taskName,
          task_definition_name: taskDefinitionName,
          task_description: taskDescription,
        },
      }

      if (window.electron) {
        const result = await window.electron.getSearchResult(query)
        searchResult = result
        searchResults.set(result)
      }
    } catch (error) {
      console.error('Error searching:', error)
    } finally {
      loading = false
    }
  }

  function hasActiveTask(projectName: string): boolean {
    // Note: This checks by project name for display purposes
    // ActiveTask now uses taskId, so we need to check by projectName from the task
    return activeTasksList.some(at => at.projectName === projectName)
  }

  function hasActiveTaskForTaskDef(taskDef: DBTaskDefinition): boolean {
    // Note: This is a simplified check - we'd need to fetch tasks to match properly
    // For now, check by name/projectName which are display fields
    return activeTasksList.some(
      at => at.name === taskDef.name && at.projectName === taskDef.projectName,
    )
  }

  function hasActiveTaskForTask(task: DBTask): boolean {
    return activeTasksList.some(
      at => at.taskId === task.id && at.date === task.date,
    )
  }

  function handleEditProject(project: DBProject) {
    projectToEdit = project
    showEditProjectModal = true
  }

  function handleDeleteProject(project: DBProject) {
    projectToDelete = project
    showDeleteProjectModal = true
  }

  function handleEditTask(task: DBTask) {
    taskToEdit = task
    showEditTaskModal = true
  }

  function handleDeleteTask(task: DBTask) {
    taskToDelete = task
    showDeleteTaskModal = true
  }

  function handleEditTaskDef(taskDef: DBTaskDefinition) {
    taskDefToEdit = taskDef
    showEditTaskDefModal = true
  }

  function handleDeleteTaskDef(taskDef: DBTaskDefinition) {
    taskDefToDelete = taskDef
    showDeleteTaskDefModal = true
  }

  function handleEditCompany(company: DBCompany) {
    companyToEdit = company
    showEditCompanyModal = true
  }

  function handleDeleteCompany(company: DBCompany) {
    companyToDelete = company
    showDeleteCompanyModal = true
  }

  function handleProjectModalClose(
    success: boolean,
    editedProject?: DBProject,
  ) {
    showEditProjectModal = false
    showDeleteProjectModal = false
    if (success && searchResult) {
      if (editedProject && projectToEdit) {
        searchResult.projects = searchResult.projects.map(p =>
          p.id === projectToEdit.id ? editedProject : p,
        )
      } else if (projectToDelete) {
        searchResult.projects = searchResult.projects.filter(
          p => p.id !== projectToDelete.id,
        )
      }
      searchResults.set(searchResult)
    }
    projectToEdit = null
    projectToDelete = null
  }

  function handleTaskModalClose(success: boolean, editedTask?: DBTask) {
    showEditTaskModal = false
    showDeleteTaskModal = false
    if (success && searchResult) {
      if (editedTask && taskToEdit) {
        searchResult.tasks = searchResult.tasks.map(t =>
          t.id === taskToEdit.id ? editedTask : t,
        )
      } else if (taskToDelete) {
        searchResult.tasks = searchResult.tasks.filter(
          t => t.id !== taskToDelete.id,
        )
      }
      searchResults.set(searchResult)
    }
    taskToEdit = null
    taskToDelete = null
  }

  function handleTaskDefModalClose(
    success: boolean,
    editedTaskDef?: DBTaskDefinition,
  ) {
    showEditTaskDefModal = false
    showDeleteTaskDefModal = false
    if (success && searchResult) {
      if (editedTaskDef && taskDefToEdit) {
        searchResult.task_definitions = searchResult.task_definitions.map(td =>
          td.id === taskDefToEdit.id ? editedTaskDef : td,
        )
      } else if (taskDefToDelete) {
        searchResult.task_definitions = searchResult.task_definitions.filter(
          td => td.id !== taskDefToDelete.id,
        )
      }
      searchResults.set(searchResult)
    }
    taskDefToEdit = null
    taskDefToDelete = null
  }

  function handleCompanyModalClose(
    success: boolean,
    editedCompany?: DBCompany,
  ) {
    showEditCompanyModal = false
    showDeleteCompanyModal = false
    if (success && searchResult) {
      if (editedCompany && companyToEdit) {
        searchResult.companies = searchResult.companies.map(c =>
          c.id === companyToEdit.id ? editedCompany : c,
        )
      } else if (companyToDelete) {
        searchResult.companies = searchResult.companies.filter(
          c => c.id !== companyToDelete.id,
        )
      }
      searchResults.set(searchResult)
    }
    companyToEdit = null
    companyToDelete = null
  }
</script>

{#if showEditCompanyModal && companyToEdit}
  <EditCompanyModal
    company={companyToEdit}
    onClose={(s, c) => handleCompanyModalClose(s, c)}
  />
{/if}

{#if showDeleteCompanyModal && companyToDelete}
  <DeleteCompanyModal
    company={companyToDelete}
    onClose={s => handleCompanyModalClose(s)}
  />
{/if}

{#if showEditProjectModal && projectToEdit}
  <EditProjectModal
    project={projectToEdit}
    onClose={(s, p) => handleProjectModalClose(s, p)}
  />
{/if}

{#if showDeleteProjectModal && projectToDelete}
  <DeleteProjectModal
    project={projectToDelete}
    onClose={s => handleProjectModalClose(s)}
  />
{/if}

{#if showEditTaskModal && taskToEdit}
  <EditTaskModal
    task={taskToEdit}
    onSuccess={(s, t) => handleTaskModalClose(s, t)}
    onClose={(s, t) => handleTaskModalClose(s, t)}
  />
{/if}

{#if showDeleteTaskModal && taskToDelete}
  <DeleteTaskModal task={taskToDelete} onClose={s => handleTaskModalClose(s)} />
{/if}

{#if showEditTaskDefModal && taskDefToEdit}
  <EditTaskDefinitionModal
    taskDefinition={taskDefToEdit}
    onClose={(s, td) => handleTaskDefModalClose(s, td)}
  />
{/if}

{#if showDeleteTaskDefModal && taskDefToDelete}
  <DeleteTaskDefinitionModal
    taskDefinition={taskDefToDelete}
    onClose={s => handleTaskDefModalClose(s)}
  />
{/if}

<section class="section">
  <h1 class="text-2xl font-bold">Search</h1>
  <h2 class="text-lg text-base-content/70">
    You can search across tasks and projects.
  </h2>

  <form onsubmit={handleSearch} class="mt-4">
    <div class="grid grid-cols-3 gap-4">
      <!-- Query Form -->
      <div class="card bg-base-200 shadow-xl">
        <div class="card-body">
          <h2 class="card-title">Query</h2>

          <div class="form-control">
            <label class="label" for="searchIn">
              <span class="label-text">Search in</span>
            </label>
            <select
              id="searchIn"
              multiple
              class="select select-bordered select-multiple"
              bind:value={searchIn}
              required
            >
              <option value="companies">Companies</option>
              <option value="projects">Projects</option>
              <option value="task_definitions">Task Definitions</option>
              <option value="tasks">Tasks</option>
            </select>
            <label class="label" for="searchIn">
              <span class="label-text-alt"
                >Hold Ctrl/Cmd to select multiple</span
              >
            </label>
          </div>

          <div class="form-control mt-2">
            <label class="label" for="fromDate">
              <span class="label-text">From</span>
            </label>
            <input
              id="fromDate"
              type="date"
              bind:value={fromDate}
              class="input input-bordered"
              required
            />
          </div>

          <div class="form-control mt-2">
            <label class="label" for="toDate">
              <span class="label-text">To</span>
            </label>
            <input
              id="toDate"
              type="date"
              bind:value={toDate}
              class="input input-bordered"
              required
            />
          </div>

          <div class="form-control mt-2">
            <label class="label" for="activeState">
              <span class="label-text">Active State</span>
            </label>
            <select
              id="activeState"
              bind:value={activeState}
              class="select select-bordered"
              required
            >
              <option value="all">All</option>
              <option value="active">Active</option>
              <option value="inactive">Inactive</option>
            </select>
          </div>

          <div class="form-control mt-2">
            <label class="label" for="companyName">
              <span class="label-text">Company Name</span>
            </label>
            <input
              id="companyName"
              type="text"
              bind:value={companyName}
              placeholder="Company Name (* for all)"
              class="input input-bordered"
              required
            />
          </div>

          <div class="form-control mt-2">
            <label class="label" for="projectName">
              <span class="label-text">Project Name</span>
            </label>
            <input
              id="projectName"
              type="text"
              bind:value={projectName}
              placeholder="Project Name (* for all)"
              class="input input-bordered"
              required
            />
          </div>

          <div class="form-control mt-2">
            <label class="label" for="taskName">
              <span class="label-text">Task Name</span>
            </label>
            <input
              id="taskName"
              type="text"
              bind:value={taskName}
              placeholder="Task Name (* for all)"
              class="input input-bordered"
              required
            />
          </div>

          <div class="form-control mt-2">
            <label class="label" for="taskDescription">
              <span class="label-text">Task Description</span>
            </label>
            <input
              id="taskDescription"
              type="text"
              bind:value={taskDescription}
              placeholder="Task Description (* for all)"
              class="input input-bordered"
              required
            />
          </div>

          <div class="form-control mt-2">
            <label class="label" for="taskDefinitionName">
              <span class="label-text">Task Definition Name</span>
            </label>
            <input
              id="taskDefinitionName"
              type="text"
              bind:value={taskDefinitionName}
              placeholder="Task Definition Name (* for all)"
              class="input input-bordered"
              required
            />
          </div>

          <div class="form-control mt-4">
            <button
              type="submit"
              class="btn btn-primary w-full"
              disabled={!formValid || loading}
            >
              {#if loading}
                <span class="loading loading-spinner"></span>
                Searching...
              {:else}
                Search
              {/if}
            </button>
          </div>
        </div>
      </div>

      <!-- Results -->
      {#if loading}
        <div class="card bg-base-200 shadow-xl col-span-2">
          <div class="card-body">
            <h2 class="card-title">Loading</h2>
            <span class="loading loading-spinner loading-lg"></span>
          </div>
        </div>
      {:else if searchResult}
        <div class="col-span-2 space-y-4">
          <!-- Companies Results -->
          {#if searchIn.includes('companies') && searchResult.companies.length > 0}
            <div class="card bg-base-200 shadow-xl">
              <div class="card-body">
                <h2 class="card-title">Companies</h2>
                <div class="space-y-2">
                  {#each searchResult.companies as company (company.id)}
                    <div class="card bg-base-100">
                      <div class="card-body">
                        <div class="flex items-center justify-between">
                          <div>
                            <h3 class="card-title text-lg">{company.name}</h3>
                            {#if company.status}
                              <span
                                class="badge {company.status === 'active'
                                  ? 'badge-success'
                                  : 'badge-error'}"
                              >
                                {company.status}
                              </span>
                            {/if}
                          </div>
                          <div class="card-actions">
                            <button
                              class="btn btn-warning btn-sm"
                              onclick={() => handleEditCompany(company)}
                            >
                              Edit
                            </button>
                            <button
                              class="btn btn-error btn-sm"
                              onclick={() => handleDeleteCompany(company)}
                            >
                              Delete
                            </button>
                          </div>
                        </div>
                      </div>
                    </div>
                  {/each}
                </div>
              </div>
            </div>
          {/if}

          <!-- Projects Results -->
          {#if searchIn.includes('projects') && searchResult.projects.length > 0}
            <div class="card bg-base-200 shadow-xl">
              <div class="card-body">
                <h2 class="card-title">Projects</h2>
                <div class="space-y-2">
                  {#each searchResult.projects as project (project.id)}
                    <div class="card bg-base-100">
                      <div class="card-body">
                        <h3 class="card-title text-lg">{project.name}</h3>
                        <div class="card-actions justify-end">
                          {#if hasActiveTask(project.name)}
                            <InfoBox type="warning" title="Warning">
                              A task belonging to this project is currently
                              active, you need to stop it to perform any action.
                            </InfoBox>
                          {:else}
                            <button
                              class="btn btn-warning btn-sm"
                              onclick={() => handleEditProject(project)}
                            >
                              Edit
                            </button>
                            <button
                              class="btn btn-error btn-sm"
                              onclick={() => handleDeleteProject(project)}
                            >
                              Delete
                            </button>
                          {/if}
                        </div>
                      </div>
                    </div>
                  {/each}
                </div>
              </div>
            </div>
          {/if}

          <!-- Task Definitions Results -->
          {#if searchIn.includes('task_definitions') && searchResult.task_definitions.length > 0}
            <div class="card bg-base-200 shadow-xl">
              <div class="card-body">
                <h2 class="card-title">Task Definitions</h2>
                <div class="space-y-2">
                  {#each searchResult.task_definitions as taskDef (taskDef.id)}
                    <div class="card bg-base-100">
                      <div class="card-body">
                        <h3 class="card-title text-lg">{taskDef.name}</h3>
                        <p class="text-sm text-base-content/70">
                          {taskDef.projectName}
                        </p>
                        <div class="card-actions justify-end">
                          {#if hasActiveTaskForTaskDef(taskDef)}
                            <InfoBox type="warning" title="Warning">
                              A task belonging to this task definition is
                              currently active, you need to stop it to perform
                              any action.
                            </InfoBox>
                          {:else}
                            <button
                              class="btn btn-warning btn-sm"
                              onclick={() => handleEditTaskDef(taskDef)}
                            >
                              Edit
                            </button>
                            <button
                              class="btn btn-error btn-sm"
                              onclick={() => handleDeleteTaskDef(taskDef)}
                            >
                              Delete
                            </button>
                          {/if}
                        </div>
                      </div>
                    </div>
                  {/each}
                </div>
              </div>
            </div>
          {/if}

          <!-- Tasks Results -->
          {#if searchIn.includes('tasks') && searchResult.tasks.length > 0}
            <div class="card bg-base-200 shadow-xl">
              <div class="card-body">
                <h2 class="card-title">Tasks</h2>
                <div class="space-y-2">
                  {#each searchResult.tasks as task (task.id)}
                    <div class="card bg-base-100">
                      <div class="card-body">
                        <h3 class="card-title text-lg">{task.name}</h3>
                        <p class="text-sm text-base-content/70">
                          {task.projectName}
                        </p>
                        {#if task.description}
                          <p class="text-sm">{task.description}</p>
                        {/if}
                        <div class="flex gap-4 text-sm">
                          <div class="flex items-center gap-1">
                            <i class="fa-solid fa-calendar"></i>
                            <span>{task.date}</span>
                          </div>
                          <div class="flex items-center gap-1">
                            <i class="fa-solid fa-clock"></i>
                            <span>{getHMSStringFromSeconds(task.seconds)}</span>
                          </div>
                        </div>
                        <div class="card-actions justify-end">
                          {#if hasActiveTaskForTask(task)}
                            <InfoBox type="warning" title="Warning">
                              This task is currently active, you need to stop it
                              to perform any action.
                            </InfoBox>
                          {:else}
                            <button
                              class="btn btn-warning btn-sm"
                              onclick={() => handleEditTask(task)}
                            >
                              Edit
                            </button>
                            <button
                              class="btn btn-error btn-sm"
                              onclick={() => handleDeleteTask(task)}
                            >
                              Delete
                            </button>
                          {/if}
                        </div>
                      </div>
                    </div>
                  {/each}
                </div>
              </div>
            </div>
          {/if}

          {#if searchResult.companies.length === 0 && searchResult.projects.length === 0 && searchResult.task_definitions.length === 0 && searchResult.tasks.length === 0}
            <div class="alert alert-info">
              <span>No results found</span>
            </div>
          {/if}
        </div>
      {/if}
    </div>
  </form>
</section>

// src/components/Search.tsx
import React, { FC, useRef, useState  } from 'react';
import moment from 'moment';
import { LoadingComponent } from './LoadingComponent';
import { EditProjectModal } from './EditProjectModal'
import { DeleteProjectModal } from './DeleteProjectModal'
import { EditTaskModal } from './EditTaskModal'
import { DeleteTaskModal } from './DeleteTaskModal'
import { DeleteTaskDefinitionModal } from './DeleteTaskDefinitionModal'
import { RootState } from './Store';
import { connect } from 'react-redux';
import { InfoboxComponent } from './InfoboxComponent';
import { watch } from 'original-fs';

type Props = {
  activeTasks: ActiveTask[]
  searchResult: SearchQueryResult
  setSearchResults: React.RefCallback<SearchQueryResult>
  setModal: React.Dispatch<React.SetStateAction<React.ReactNode>>
}

type SearchResultsComponentProps = {
  activeTasks: ActiveTask[]
  searchResult: SearchQueryResult
  setSearchResults: React.RefCallback<SearchQueryResult>
  searchIn: React.RefObject<HTMLSelectElement>
  setModal: React.Dispatch<React.SetStateAction<React.ReactNode>>
}


const SearchResultsProjectsComponent: FC<Props> = ({ activeTasks, searchResult, setSearchResults, setModal }) => {

  const delModalCallback = (status: boolean, data: DBProject) => {
    if (status) {
      const filteredProjects = searchResult.projects.filter((project: DBProject) => project.name !== data.name);
      searchResult.projects = filteredProjects;
      setSearchResults(searchResult);
    }
    setModal(null)
  }

  const showDeleteConfirmModal = (evt: React.MouseEvent<HTMLButtonElement>) => {
    evt.preventDefault();
    const data = JSON.parse(evt.currentTarget.dataset.data) as DBProject;
    setModal(<DeleteProjectModal project={data} callback={(status) => delModalCallback(status, data)} />);
  }

  const editModalCallback = (status: boolean, data: DBProject, editedData: DBProject) => {
    if (status) {
      const filteredProjects = searchResult.projects.map((project: DBProject) => {
        if (project.name === data.name) {
          data.name = editedData.name;
          return data;
        }
        return project;
      });
      searchResult.projects = filteredProjects;
      setSearchResults(searchResult);
    }
    setModal(null)
  }

  const showEditModal = (evt: React.MouseEvent<HTMLButtonElement>) => {
    evt.preventDefault();
    const data = JSON.parse(evt.currentTarget.dataset.data) as DBProject;
    setModal(<EditProjectModal project={data} callback={(status: boolean, editedData: DBProject) => editModalCallback(status, data, editedData)} />);
  }

  type ButtonWrapperProps = {
    project: DBProject
  }

  const ButtonWrapperComponent: FC<ButtonWrapperProps> = ({ project }) => {
    const activeTask = activeTasks.find((at) => at.project_name === project.name)
    if (activeTask) {
      return <>
        <InfoboxComponent title="Warning" type="warning">
          A task belonging to this project is currently active,
          you need to stop it to perform any action.
        </InfoboxComponent>
      </>
    } else {
      return <>
        <button className="button is-warning" data-data={JSON.stringify(project)} onClick={showEditModal}>Edit</button>
        <button className="button is-danger" data-data={JSON.stringify(project)} onClick={showDeleteConfirmModal}>Delete</button>
      </>
    }
  }

  return <>
    <div>
      <div className="field">
        <div className="control">
          <section className="hero">
            <div className="hero-body">
              <p className="title">Projects</p>
            </div>
          </section>
        </div>
      </div>
      { searchResult.projects.length ?
        searchResult.projects.map((project: DBProject, idx: number) =>
          <div key={idx} className="columns panel-block">
            <div className="column">
              {project.name}
            </div>
            <div className="column">
              <div className="field">
                <div className="control">
                  <ButtonWrapperComponent project={project} />
                </div>
              </div>
            </div>
          </div>
        )
        : <div>No projects found</div>
      }
    </div>
  </>;
}

const SearchResultsTaskDefinitionsComponent: FC<Props> = ({ activeTasks, searchResult, setModal, setSearchResults }) => {
  const delModalCallback = (status: boolean, data: DBTaskDefinition) => {
    if (status) {
      const f = (td: DBTaskDefinition) => {
        if (td.name !== data.name || td.project_name !== data.project_name) {
          return td;
        }
      }
      searchResult.task_definitions = searchResult.task_definitions.filter(f);
      setSearchResults(searchResult);
    }
    setModal(null)
  }

  const showDeleteConfirmModal = (evt: React.MouseEvent<HTMLButtonElement>) => {
    evt.preventDefault();
    const data = JSON.parse(evt.currentTarget.dataset.data) as DBTaskDefinition;
    setModal(<DeleteTaskDefinitionModal taskDefinition={data} callback={(status) => delModalCallback(status, data)} />);
  }

  type ButtonWrapperProps = {
    taskdef: DBTaskDefinition
  }

  const ButtonWrapperComponent: FC<ButtonWrapperProps> = ({ taskdef }) => {
    const activeTask = activeTasks.find((at) => at.name === taskdef.name && at.project_name === taskdef.project_name)
    if (activeTask) {
      return <>
        <InfoboxComponent title="Warning" type="warning">
          A task belonging to this task definition is currently active,
          you need to stop it to perform any action.
        </InfoboxComponent>
      </>
    } else {
      return <>
        <button className="button is-warning" data-data={JSON.stringify(taskdef)}>Edit</button>
        <button className="button is-danger" data-data={JSON.stringify(taskdef)} onClick={showDeleteConfirmModal}>Delete</button>
      </>
    }
  }

  return <>
    <div>
      <div className="field">
        <div className="control">
          <section className="hero">
            <div className="hero-body">
              <p className="title">Task Definitions</p>
            </div>
          </section>
        </div>
      </div>
      { searchResult.task_definitions.length ?
        searchResult.task_definitions.map((taskdef: DBTaskDefinition, idx: number) =>
          <div key={idx} className="columns panel-block">
            <div className="column">
              {taskdef.name}
            </div>
            <div className="column">
              <div className="field">
                <div className="control">
                  <ButtonWrapperComponent taskdef={taskdef} />
                </div>
              </div>
            </div>
          </div>
        )
        : <div>No task definitions found</div>
      }
    </div>
  </>;
}
const SearchResultsTasksComponent: FC<Props> = ({ activeTasks, searchResult, setModal, setSearchResults }) => {
  const delModalCallback = (status: boolean, data: DBTask) => {
    if (status) {
      const f = (t: DBTask) => {
        if (t.name !== data.name || t.project_name !== data.project_name || t.date !== data.date) {
          return t;
        }
      }
      searchResult.tasks = searchResult.tasks.filter(f);
      setSearchResults(searchResult);
    }
    setModal(null)
  }

  const showDeleteConfirmModal = (evt: React.MouseEvent<HTMLButtonElement>) => {
    evt.preventDefault();
    const data = JSON.parse(evt.currentTarget.dataset.data) as DBTask;
    setModal(<DeleteTaskModal task={data} callback={(status) => delModalCallback(status, data)} />);
  }

  type ButtonWrapperProps = {
    task: DBTask
  }

  const ButtonWrapperComponent: FC<ButtonWrapperProps> = ({ task }) => {
    const activeTask = activeTasks.find((at) => at.name === task.name && at.project_name === task.project_name)
    if (activeTask) {
      return <>
        <InfoboxComponent title="Warning" type="warning">
          This task is currently active,
          you need to stop it to perform any action.
        </InfoboxComponent>
      </>
    } else {
      return <>
        <button className="button is-warning" data-data={JSON.stringify(task)}>Edit</button>
        <button className="button is-danger" data-data={JSON.stringify(task)} onClick={showDeleteConfirmModal}>Delete</button>
      </>
    }
  }

  return <>
    <div>
      <div className="field">
        <div className="control">
          <section className="hero">
            <div className="hero-body">
              <p className="title">Tasks</p>
            </div>
          </section>
        </div>
      </div>
      { searchResult.tasks.length ?
        searchResult.tasks.map((task: DBTask, idx: number) =>
          <div key={idx} className="columns panel-block">
            <div className="column">
              {task.name} - {task.project_name}
              <div>
                {task.description}
              </div>
            </div>
            <div className="column">
              <div className="field">
                <div className="control">
                  <ButtonWrapperComponent task={task} />
                </div>
              </div>
            </div>
          </div>
        )
        : <div>No tasks found</div>
      }
    </div>
  </>;
}


const SearchResultsComponent: FC<SearchResultsComponentProps> = ({ activeTasks, searchIn, searchResult, setModal, setSearchResults}) => {
  if (!searchResult) {
    return null;
  }
  const form = searchIn.current.closest('form') as HTMLFormElement;
  const formData = new FormData(form);
  const si = formData.getAll('search_in') as string[];
  return <>
    { si.includes('projects') ? <SearchResultsProjectsComponent activeTasks={activeTasks} setModal={setModal} searchResult={searchResult} setSearchResults={setSearchResults} /> : null }
    { si.includes('task_definitions') ? <SearchResultsTaskDefinitionsComponent activeTasks={activeTasks} setModal={setModal} searchResult={searchResult} setSearchResults={setSearchResults} /> : null }
    { si.includes('tasks') ? <SearchResultsTasksComponent activeTasks={activeTasks} setModal={setModal} searchResult={searchResult} setSearchResults={setSearchResults} /> : null }
  </>;
}

type ComponentProps = {
  activeTasks: ActiveTask[]
}

const Component: FC<ComponentProps> = ({ activeTasks }) => {
  const [searchResult, setSearchResults] = useState<SearchQueryResult>(null);
  const [showLoading, setLoading] = useState<boolean>(false);
  const [modal, setModal] = useState<React.ReactNode>(null);

  const searchRef = useRef<HTMLButtonElement>(null)
  const searchInRef = useRef<HTMLSelectElement>(null)

  // This is by intention on every input element, instead of the form element onChange,
  // because there seems to be a bug, where the onChange does not get triggered after a change
  // on the input element has occured.
  const onInputChange = (e: React.FormEvent<HTMLInputElement | HTMLSelectElement>) => {
    const form = e.currentTarget.closest('form') as HTMLFormElement;
    const isFormValid = form.checkValidity();
    const input = e.currentTarget as HTMLInputElement;
    const icon = input.nextElementSibling?.children[0];
      if (icon) {
        if (input.checkValidity()) {
          icon.classList.remove('has-text-danger');
          icon.classList.remove('fa-xmark');
          icon.classList.add('has-text-success');
          icon.classList.add('fa-check');
        } else {
          icon.classList.remove('has-text-success');
          icon.classList.remove('fa-check');
          icon.classList.add('has-text-danger');
          icon.classList.add('fa-xmark');
        }
      }
    if (!isFormValid) {
      searchRef.current?.setAttribute('disabled', 'disabled');
      searchRef.current?.classList.remove('is-primary');
      searchRef.current?.classList.add('is-danger');
    } else {
      searchRef.current?.removeAttribute('disabled');
      searchRef.current?.classList.add('is-primary');
      searchRef.current?.classList.remove('is-danger');
    }
  }

  const onFormSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();

    const form = e.currentTarget as HTMLFormElement;
    const isFormValid = form.checkValidity();
    if (!isFormValid) {
      return;
    }
    searchRef.current?.classList.add('is-loading');
    setSearchResults(null);
    setLoading(true);
    const formData = new FormData(form);
    const rawfrom = formData.get('from_date') as string;
    const rawto = formData.get('to_date') as string;
    const from_date = moment(rawfrom).format('YYYY-MM-DD');
    const to_date = moment(rawto).format('YYYY-MM-DD');
    const active_state = formData.get('active_state') as string;
    const project_name = formData.get('project_name') as string;
    const task_name = formData.get('task_name') as string;
    const task_definition_name = formData.get('task_definition_name') as string;
    const task_description = formData.get('task_description') as string;
    const query: SearchQuery = {
      search_in: formData.getAll('search_in') as string[],
      from_date,
      to_date,
      active_state,
      task: {
        project_name,
        task_name,
        task_definition_name,
        task_description,
      }
    };
    const rpcResult = await window.electron.getSearchResult(query);
    setLoading(false);
    setSearchResults(rpcResult);
    searchRef.current?.classList.remove('is-loading');
  }

  return <>
    {modal ? modal : null}
    <section className="section">
      <h1 className="title">Search</h1>
      <h2 className="subtitle">You can export search across tasks and projects.</h2>
      <form className="search-form" onSubmit={onFormSubmit}>
        <div className="fixed-grid has-2-cols">
          <div className="grid">
            <div className="cell">
              <nav className="panel">
                <p className="panel-heading">Query</p>
                <div className="field">
                  <label className="label">Search in</label>
                  <div className="control has-icons-right select is-multiple">
                    <select ref={searchInRef} required onChange={onInputChange} multiple name="search_in">
                      <option value="tasks">Tasks</option>
                      <option value="projects">Projects</option>
                      <option value="task_definitions">Task Definitions</option>
                    </select>
                  </div>
                </div>
                <div className="field">
                  <label className="label">From</label>
                  <div className="control has-icons-right">
                    <input name="from_date" required defaultValue={moment().format('YYYY-MM-DD')} onChange={onInputChange} className="input" type="date" />
                    <span className="icon is-small is-right">
                      <i className="fas fa-check has-text-success"></i>
                    </span>
                  </div>
                </div>
                <div className="field">
                  <label className="label">To</label>
                  <div className="control has-icons-right">
                    <input name="to_date" required defaultValue={moment().format('YYYY-MM-DD')} onChange={onInputChange} className="input" type="date" />
                    <span className="icon is-small is-right">
                      <i className="fas fa-check has-text-success"></i>
                    </span>
                  </div>
                </div>
                <div className="field">
                  <label className="label">Active State</label>
                  <div className="control">
                    <div className="select">
                      <select required onChange={onInputChange} name="active_state">
                        <option value="all">All</option>
                        <option value="active">Active</option>
                        <option value="inactive">Inactive</option>
                      </select>
                    </div>
                  </div>
                </div>
                <div className="field">
                  <label className="label">Project Name</label>
                  <div className="control has-icons-right">
                    <input required onChange={onInputChange} name="project_name" defaultValue="*" className="input" type="text" placeholder="Project Name" />
                    <span className="icon is-small is-right">
                      <i className="fas fa-check has-text-success"></i>
                    </span>
                  </div>
                </div>
                <div className="field">
                  <label className="label">Task Name</label>
                  <div className="control has-icons-right">
                    <input required onChange={onInputChange} name="task_name" defaultValue="*" className="input" type="text" placeholder="Task Name" />
                    <span className="icon is-small is-right">
                      <i className="fas fa-check has-text-success"></i>
                    </span>
                  </div>
                </div>
                <div className="field">
                  <label className="label">Task Description</label>
                  <div className="control has-icons-right">
                    <input required onChange={onInputChange} name="task_description" defaultValue="*" className="input" type="text" placeholder="Task Description" />
                    <span className="icon is-small is-right">
                      <i className="fas fa-check has-text-success"></i>
                    </span>
                  </div>
                </div>
                <div className="field">
                  <label className="label">Task Definition Name</label>
                  <div className="control has-icons-right">
                    <input required onChange={onInputChange} name="task_definition_name" defaultValue="*" className="input" type="text" placeholder="Task Definition Name" />
                    <span className="icon is-small is-right">
                      <i className="fas fa-check has-text-success"></i>
                    </span>
                  </div>
                </div>
                <div className="field">
                  <div className="control">
                    <button ref={searchRef} className="button is-primary" type="submit">Search</button>
                  </div>
                </div>
              </nav>
            </div>

            {showLoading ?
              <div className="cell">
                <nav className="panel">
                  <p className="panel-heading">Loading</p>
                  <div className="field">
                    <LoadingComponent />
                  </div>
                </nav>
              </div>
              : null}

            {searchResult ?
              <div className="cell">
                <nav className="panel">
                  <p className="panel-heading">Results</p>
                  <div className="field">
                    <SearchResultsComponent
                      activeTasks={activeTasks}
                      setModal={setModal}
                      searchIn={searchInRef}
                      setSearchResults={setSearchResults}
                      searchResult={searchResult} />
                  </div>
                </nav>
              </div>
              : null}

          </div>
        </div>
      </form>
    </section>
  </>;
};

const mapStateToProps = (state: RootState) => {
  return {
    activeTasks: state.activeTasks.value
  }
}
const connected = connect(mapStateToProps)(Component);
export const Search = connected
