// src/renderer/src/components/TaskDefinitions.svelte
<script lang="ts">
  import { onMount } from 'svelte'
  import {
    taskDefinitions,
    selectedProject,
    activeTasks,
    selectedTaskDefinition,
  } from '../stores'
  import EditTaskDefinitionModal from './modals/EditTaskDefinitionModal.svelte'
  import DeleteTaskDefinitionModal from './modals/DeleteTaskDefinitionModal.svelte'
  import InfoBox from './InfoBox.svelte'

  let taskDefs: DBTaskDefinition[] = []
  let showEditModal = false
  let showDeleteModal = false
  let taskDefToEdit: DBTaskDefinition | null = null
  let taskDefToDelete: DBTaskDefinition | null = null

  $: selectedProj = $selectedProject
  $: activeTasksList = $activeTasks

  onMount(async () => {
    taskDefinitions.subscribe(value => {
      taskDefs = value
    })

    selectedProject.subscribe(async proj => {
      if (proj.name) {
        await fetchTaskDefinitions(proj.name)
      }
    })
  })

  async function fetchTaskDefinitions(projectName: string) {
    if (window.electron) {
      try {
        const data = (
          await window.electron.getTaskDefinitions(projectName)
        ).filter((taskDef: DBTaskDefinition) => taskDef.status === 'active')
        taskDefinitions.set(data)
      } catch (error) {
        console.error('Error loading task definitions:', error)
      }
    }
  }

  async function handleAddTaskDefinition(e: Event) {
    e.preventDefault()
    if (!selectedProj.name) return

    const form = e.target as HTMLFormElement
    const formData = new FormData(form)
    const name = formData.get('name') as string

    if (name && window.electron) {
      const result = await window.electron.addTaskDefinition({
        name,
        project_name: selectedProj.name,
      })
      if (result.success) {
        await fetchTaskDefinitions(selectedProj.name)
        form.reset()
      }
    }
  }

  function handleTaskDefSelect(taskDef: DBTaskDefinition) {
    selectedTaskDefinition.set(taskDef)
  }

  function handleEditClick(taskDef: DBTaskDefinition) {
    taskDefToEdit = taskDef
    showEditModal = true
  }

  function handleDeleteClick(taskDef: DBTaskDefinition) {
    taskDefToDelete = taskDef
    showDeleteModal = true
  }

  function handleEditModalClose(
    success: boolean,
    editedTaskDef?: DBTaskDefinition,
  ) {
    showEditModal = false
    if (success && editedTaskDef) {
      selectedTaskDefinition.set(editedTaskDef)
      if (selectedProj.name) {
        fetchTaskDefinitions(selectedProj.name)
      }
    }
    taskDefToEdit = null
  }

  function handleDeleteModalClose(success: boolean) {
    showDeleteModal = false
    if (success) {
      selectedTaskDefinition.set(null)
      if (selectedProj.name) {
        fetchTaskDefinitions(selectedProj.name)
      }
    }
    taskDefToDelete = null
  }

  function hasActiveTask(taskDefName: string): boolean {
    return activeTasksList.some(
      at => at.name === taskDefName && at.project_name === selectedProj.name,
    )
  }

  function isSelected(taskDef: DBTaskDefinition): boolean {
    const selected = $selectedTaskDefinition
    return (
      selected?.name === taskDef.name &&
      selected?.project_name === taskDef.project_name
    )
  }
</script>

{#if showEditModal && taskDefToEdit}
  <EditTaskDefinitionModal
    taskDefinition={taskDefToEdit}
    onClose={handleEditModalClose}
  />
{/if}

{#if showDeleteModal && taskDefToDelete}
  <DeleteTaskDefinitionModal
    taskDefinition={taskDefToDelete}
    onClose={handleDeleteModalClose}
  />
{/if}

{#if selectedProj.name}
  <section class="section">
    <h1 class="text-2xl font-bold">Task Definitions</h1>
    <h2 class="text-lg text-base-content/70">
      All available task definitions for a given project
    </h2>

    <div class="grid grid-cols-3 gap-4 mt-4">
      <!-- New Task Definition -->
      <div class="card bg-base-200 shadow-xl">
        <div class="card-body">
          <h2 class="card-title">New</h2>
          <form on:submit={handleAddTaskDefinition}>
            <div class="form-control">
              <label class="label">
                <span class="label-text">Task Definition Name</span>
              </label>
              <input
                type="text"
                name="name"
                placeholder="Task Definition Name"
                class="input input-bordered"
                required
              />
            </div>
            <div class="form-control mt-4">
              <button type="submit" class="btn btn-primary"
                >Add Task Definition</button
              >
            </div>
          </form>
        </div>
      </div>

      <!-- Available Task Definitions -->
      {#if taskDefs.length > 0}
        <div class="card bg-base-200 shadow-xl">
          <div class="card-body">
            <h2 class="card-title">Available</h2>
            <div class="space-y-2">
              {#each taskDefs as taskDef}
                <div
                  class="p-3 rounded cursor-pointer transition-colors flex items-center gap-2"
                  class:bg-primary={isSelected(taskDef)}
                  class:text-primary-content={isSelected(taskDef)}
                  on:click={() => handleTaskDefSelect(taskDef)}
                >
                  <i class="fa-solid fa-book"></i>
                  <p class="font-semibold">{taskDef.name}</p>
                </div>
              {/each}
            </div>
          </div>
        </div>
      {/if}

      <!-- Actions -->
      {#if $selectedTaskDefinition}
        <div class="card bg-base-200 shadow-xl">
          <div class="card-body">
            <h2 class="card-title">Actions</h2>
            {#if hasActiveTask($selectedTaskDefinition.name)}
              <InfoBox type="warning" title="Warning">
                A task belonging to this task definition is currently active,
                you need to stop it to perform any action.
              </InfoBox>
            {:else}
              <div class="flex gap-2">
                <button
                  class="btn btn-warning"
                  on:click={() => handleEditClick($selectedTaskDefinition!)}
                >
                  Edit
                </button>
                <button
                  class="btn btn-error"
                  on:click={() => handleDeleteClick($selectedTaskDefinition!)}
                >
                  Delete
                </button>
              </div>
            {/if}
          </div>
        </div>
      {/if}
    </div>
  </section>
{/if}

// src/components/TaskDefinitions.tsx
import { FC, useState } from 'react';
import { connect } from 'react-redux';
import { RootState } from './Store';
import { DeleteTaskDefinitionModal } from './DeleteTaskDefinitionModal';
import { useAppDispatch, useAppSelector } from './Store/hooks'
import { appendTaskDefinition } from './Store/slices/taskDefinitions'
import { setSelectedTaskDefinition } from './Store/slices/selectedTaskDefinition'
import { EditTaskDefinitionModal } from './EditTaskDefinitionModal';
import clsx from 'clsx';

type Props = {
  taskDefinitions: DBTaskDefinition[]
  activeTasks: ActiveTask[]
  selectedProject: DBProject
}

const Component: FC<Props> = ({ activeTasks, selectedProject, taskDefinitions }) => {
  const dispatch = useAppDispatch();
  const selectedTaskDefinition = useAppSelector((state) => state.selectedTaskDefinition.value)
  const [modal, setModal] = useState(null)

  const onFormSubmit = async (evt: React.FormEvent) => {
    evt.preventDefault();
    const form = evt.target as HTMLFormElement;
    const formData = new FormData(form);
    const name = formData.get("name") as string
    const project_name = selectedProject.name
    const rpcResult = await window.electron.addTaskDefinition({
      name,
      project_name
    })
    if (rpcResult.success) {
      dispatch(appendTaskDefinition({ name, project_name: project_name }));
    }
  }

  const onEditCallback = async (status: boolean, data: DBTaskDefinition) => {
    if (status) {
      dispatch(setSelectedTaskDefinition({ name: data.name, project_name: data.project_name }));
    }
    setModal(null)
  }

  const onEditButtonClick = async (evt: React.MouseEvent) => {
    evt.preventDefault();
    setModal(<EditTaskDefinitionModal taskDefinition={selectedTaskDefinition} callback={onEditCallback} />)
  }

  const onDeleteCallback = () => {
    setModal(null)
  }

  const onDeleteButtonClick = async (evt: React.MouseEvent) => {
    evt.preventDefault();
    setModal(<DeleteTaskDefinitionModal taskDefinition={selectedTaskDefinition} callback={onDeleteCallback} />)
  }

  const onTaskDefintionSelect = async (evt: React.MouseEvent) => {
    evt.preventDefault();
    const target = evt.target as HTMLDivElement
    const root = target.closest('[data-name]') as HTMLDivElement
    const name = root.dataset.name as string
    const project_name = root.dataset.projectName as string
    dispatch(setSelectedTaskDefinition({ name, project_name }))
  }

  const ButtonWrapperComponent: FC = () => {
    const activeTask = activeTasks.find((at) => at.name === selectedTaskDefinition.name && at.project_name === selectedTaskDefinition.project_name)
    if (activeTask) {
      return <>
        <article className="message is-warning">
          <div className="message-header">
            <p>Warning</p>
          </div>
          <div className="message-body">
            Task is currently active, please stop it before deleting or editing.
          </div>
        </article>
      </>
    } else {
      return <>
        <button className="button is-warning m-1" onClick={onEditButtonClick}>Edit</button>
        <button className="button is-danger m-1" onClick={onDeleteButtonClick}>Delete</button>
      </>
    }
  }

  return <>
    {modal}
    {selectedProject.name ?
      <section className="section" data-taskdef-section>
        <h1 className="title">Tasksdefinitions</h1>
        <h2 className="subtitle">All available Tasksdefs for a given project</h2>
          <div className="fixed-grid has-3-cols">
            <div className="grid">
              <div className="cell">
                <nav className="panel">
                  <p className="panel-heading">New</p>
                  <form onSubmit={onFormSubmit} className="p-4">
                    <div className="field">
                      <label className="label">Taskdef Name</label>
                      <div className="control">
                        <input name="name" className="input" type="text" placeholder="Taskdef Name" />
                      </div>
                    </div>
                    <div className="field">
                      <div className="control">
                        <button className="button is-primary" type="submit">Add Taskdef</button>
                      </div>
                    </div>
                  </form>
                </nav>
              </div>

            { taskDefinitions.length ?
              <div className="cell">
                <nav className="panel">
                  <p className="panel-heading">Available</p>
                  <div>
                    { taskDefinitions.map((taskdef, idx: number) => (
                      <div key={idx} onClick={onTaskDefintionSelect} className={clsx('panel-block', (taskdef.name === selectedTaskDefinition.name && taskdef.project_name && selectedTaskDefinition.project_name ? 'is-active' : null))} data-idx={idx} data-project-name={taskdef.project_name} data-name={taskdef.name}>
                        <span className="panel-icon">
                          <i className="fas fa-book" aria-hidden="true"></i>
                        </span>
                        <p className="bd-notification is-info">{taskdef.name}</p>
                      </div>
                    )) }
                  </div>
                </nav>
              </div>
            : null }

            { selectedTaskDefinition.name ?
              <div data-taskdef-actions-container className="cell">
                <nav className="panel">
                  <p className="panel-heading">Actions</p>
                  <form data-buttons className="p-4">
                    <div className="field">
                      <div data-buttons className="control">
                        <ButtonWrapperComponent />
                      </div>
                    </div>
                  </form>
                </nav>
              </div>
            : null }

          </div>
        </div>
      </section>
    : null }
  </>;
};

const mapStateToProps = (state: RootState) => {
  return {
    taskDefinitions: state.taskDefinitions.value,
    selectedProject: state.selectedProject.value,
    activeTasks: state.activeTasks.value
  }
}
const connected = connect(mapStateToProps)(Component);
export const TaskDefinitions = connected
